# Docker Compose configuration for Papertrail MCP Server
# For local development and testing

version: '3.8'

services:
  papertrail-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: papertrail-mcp-server:latest
    container_name: papertrail-mcp-server
    
    # Environment configuration
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - MCP_SERVER_NAME=papertrail-mcp
      - MCP_SERVER_VERSION=1.0.0
      - RATE_LIMIT_REQUESTS_PER_MINUTE=60
      - RATE_LIMIT_BURST=10
    
    # Load environment variables from .env file
    env_file:
      - .env
    
    # Port mapping (for HTTP endpoints if needed)
    ports:
      - "3001:3001"
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Restart policy
    restart: unless-stopped
    
    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem (with writable tmp)
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    
    # Network configuration
    networks:
      - mcp-network

# Network configuration
networks:
  mcp-network:
    driver: bridge
    name: mcp-network

# Volume configuration (if needed for persistent data)
volumes:
  mcp-data:
    driver: local
